config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # TODO: Move to /users/settings?
  resource   :preferences, only: %i[show update]

  resources :groups
  resources :subscriptions, only: %i[index create destroy]
  resources :activities do
    get 'export'
    post 'approve'
  end
  resources :assignments, only: %i[index create destroy]

  root 'welcome#index'
end

app/models/group.rb
# Defines a Group. Users can subscribe to groups, and thus recieve notifications
# of assigned activities.
class Group < ApplicationRecord
  validates :name, presence: { message: I18n.t('error.brief.no_blank') },
                   uniqueness: { message: I18n.t('error.brief.unique') }

  validates :creator, presence: { message: I18n.t('error.brief.log_in') }

  has_many :subscriptions, dependent: :destroy
  has_many :users, -> { distinct }, through: :subscriptions

  has_many :assignments, dependent: :destroy
  has_many :activities, -> { distinct }, through: :assignments

  belongs_to :creator,
             class_name: 'User',
             foreign_key: :creator_id,
             inverse_of: :created_groups
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    @group.creator = current_user if user_signed_in?

    if @group.save
      redirect_to @group
    else
      render 'new', status: :bad_request
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit', status: :bad_request
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= semantic_form_for group do |f|
  = f.inputs do
    = f.input :name
    = f.input :description
  = f.actions do
    = f.action :submit, as: :button
    = f.action :cancel, as: :link

app/views/groups/edit.html.haml
%h1
  = t 'buttons.group.edit'

= render 'form', action: 'edit', group: @group

app/views/groups/index.html.haml
%h1 Groups
- if can? :create, Group
  = link_to t('buttons.group.new'), new_group_path
%ul
  - @groups.each do |group|
    %li
      = link_to group.name, group_path(group)

app/views/groups/new.html.haml
%h1
  = t 'buttons.group.new'

= render 'form', action: 'new', group: @group

app/views/groups/show.html.haml
%h1
  \##{@group.id}:
  %em= @group.name
%p
%em
  = @group.description || t('labels.group.no_description')
%p
  = render 'subscriptions/button', group: @group
%p
  - if can? :edit, @group
    = link_to t('buttons.group.edit'), edit_group_path(@group)
    |
  = link_to t('buttons.general.back'), groups_path