config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # TODO: Move to /users/settings?
  resource   :preferences, only: %i[show update]

  resources :groups
  resources :subscriptions, only: %i[index create destroy]
  resources :activities do
    get 'export'
    post 'approve'
  end
  resources :assignments, only: %i[index create destroy]

  root 'welcome#index'
end

app/models/activity.rb
# Defines an activity.
# TODO: Massive refactor
class Activity < ApplicationRecord
  # Official Ministry of Education guidelines from the EOTC Guidelines 2016
  # Source: http://eotc.tki.org.nz/EOTC-home/EOTC-Guidelines
  # Accessed Friday December 7, 2018
  ACTIVITY_DATA = {
    in_school: {
      low_risk: {
        approval: :none,
        parental_consent: :none,
        risk_management_planning: :usual_lesson_planning
      }, high_risk: {
        approval: :blanket,
        parental_consent: :blanket,
        risk_management_planning: %i[usual_lesson_planning generic]
      }
    },
    community: {
      low_risk: {
        approval: %i[senior_teacher coordinator],
        parental_consent: %i[none blanket],
        risk_management_planning: :generic
      }, high_risk: {
        approval: %i[senior_teacher coordinator],
        parental_consent: %i[blanket separate],
        risk_management_planning: :generic
      }
    },
    day_trip: {
      low_risk: {
        approval: %i[senior_teacher coordinator],
        parental_consent: %i[none blanket],
        risk_management_planning: :generic
      }, high_risk: {
        approval: %i[principal coordinator],
        parental_consent: :separate_and_risk_disclosure,
        risk_management_planning: :specific
      }
    },
    multi_day: {
      low_risk: {
        approval: %i[principal coordinator],
        parental_consent: :separate,
        risk_management_planning: :specific
      }, high_risk: {
        approval: %i[principal board],
        parental_consent: :separate_and_risk_disclosure,
        risk_management_planning: :specific
      }
    }
  }.freeze

  validates :name, presence: { message: I18n.t('error.brief.no_blank') },
                   uniqueness: { message: I18n.t('error.brief.unique') }

  validates :creator, presence: { message: I18n.t('error.brief.log_in') }

  has_many :assignments, dependent: :destroy
  has_many :groups, -> { distinct }, through: :assignments

  has_many :users, through: :groups

  belongs_to :creator,
             class_name: 'User',
             foreign_key: :creator_id,
             inverse_of: :created_activities

  def can_be_approved_by?(user)
    approval = Array(approval_needed)
    user.role.to_sym.in?(approval) || user.role?(:administrator)
  end

  def parental_consent
    data = ACTIVITY_DATA[activity_type.to_sym][risk.to_sym]
    data[:parental_consent]
  end

  def planning
    data = ACTIVITY_DATA[activity_type.to_sym][risk.to_sym]
    data[:risk_management_planning]
  end

  def approved?
    return true  if approval_needed == :none
    return false if approved_at.nil?

    approved_at >= (edited_at || created_at)
  end

  def valid_types
    a = %i[in_school community day_trip multi_day].map do |i|
      [I18n.t("labels.activity.type.#{i}.brief"), i]
    end
    [*a].to_h
  end

  def valid_risks
    a = %i[low high].map do |i|
      [I18n.t("labels.activity.risk_level.#{i}"), i]
    end
    [*a].to_h
  end

  def notify_subscribers?
    applicable_users = users.keep_if do |user|
      user.should_be_notified_by(self)
    end

    applicable_users.each do |user|
      mailer = NotificationsMailer.with user: user,
                                        activity: self
      mailer.activity_upcoming.deliver_now
    end
  end

  private

  def approval_needed
    data = ACTIVITY_DATA[activity_type.to_sym][(risk.to_s + '_risk').to_sym]
    data[:approval]
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  load_and_authorize_resource

  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def export
    @activity = Activity.find(params[:activity_id])

    filename_elements = ['activity', @activity.name,
                         @activity.occurs_at]

    filename_elements.map! { |e| e.to_s.parameterize }
    filename_elements.reject!(&:blank?)

    @filename = "#{filename_elements.join('-')}.pdf"

    respond_to do |format|
      format.pdf
      format.csv
    end
  end

  def new
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)

    @activity.creator = current_user if user_signed_in?
    @activity.edited_at = @activity.created_at

    if @activity.save
      redirect_to @activity
    else
      render 'new', status: :bad_request
    end
  end

  def update
    @activity = Activity.find(params[:id])

    redirect_to @activity unless would_change(activity_params, @activity)

    @activity.update! activity_params.merge(edited_at: Time.current)
  end

  def approve
    @activity = Activity.find(params[:activity_id])
    authorize! :approve, @activity

    @activity.update! approved_at: Time.current
  end

  private

  def activity_params
    params.require(:activity).permit(:name,
                                     :description,
                                     :activity_type,
                                     :risk,
                                     :groups)
  end

  def would_change(some_params, activity)
    would_change_param(some_params[:name], activity.name) ||
      would_change_param(some_params[:description], activity.description) ||
      would_change_param(some_params[:activity_type], activity.activity_type) ||
      would_change_param(some_params[:risk], activity.risk)
  end

  def would_change_param(param, activity_param)
    !param.nil? && param != activity_param
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_approve_button.html.haml
- if !activity.approved? && can?(:approve, activity)
  = button_to t('buttons.activity.approve'),
    activity_approve_url(activity),
    method: :post

app/views/activities/_examples.html.haml
- @activity.valid_types.values.each do |activity_type|
  - @activity.valid_risks.values.each do |risk|
    %ul{ id: 'example_' + activity_type.to_s + '_' + risk.to_s,
         class: 'activity_example_list hidden' }
      - t("labels.activity.examples.#{activity_type}.#{risk}_risk").each do |e|
        %li.activity_example= e

app/views/activities/_form.html.haml
= semantic_form_for activity do |f|
  = f.inputs do
    = f.input :name
    = f.input :description
    = f.input :activity_type, as: :radio,
              collection: activity.valid_types
    = f.input :risk,          as: :radio,
              collection: activity.valid_risks
    = f.input :groups, as: :check_boxes
  = render 'examples'
  = f.actions do
    = f.action :submit, as: :button
    = f.action :cancel, as: :link

app/views/activities/edit.html.haml
%h1
  = t 'buttons.activity.edit'

= render 'form', action: 'update', activity: @activity

app/views/activities/index.html.haml
%h1 Activities
- if can? :create, Activity
  = link_to t('buttons.activity.new'), new_activity_path
%ul
  - @activities.each do |activity|
    - if can? :read, activity
      %li
        = link_to activity.name, activity_path(activity)

app/views/activities/new.html.haml
%h1
  = t 'buttons.activity.new'

= render 'form', action: 'new', activity: @activity

app/views/activities/show.html.haml
%h1
  \##{@activity.id}:
  %em= @activity.name
%p
  = render 'approve_button', activity: @activity
%p
  Type:
  = t("labels.activity.type.#{@activity.activity_type}.brief")
%p
  Risk level:
  = t("labels.activity.risk.#{@activity.risk}")
%em
  = @activity.description || t('labels.activity.no_description')
%p
  In groups:
  %ol
    - @activity.groups.each do |group|
      %li
        = link_to group.name, group
%p
  - if can? :edit, @activity
    = link_to t('buttons.activity.edit'), edit_activity_path(@activity)
    |
  = link_to t('buttons.general.back'), activities_path